import Head from 'next/head';

import styles from '../styles/Home.module.css';
import TermAndUse from './Components/TermAndUse';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"></link>
      </Head>

    
<TermAndUse />
     
    </div>
  )
}
